"""Agent domain models — typed schemas for AI-generated publishing plans.

All agent output is structured into these models and validated before
any publishing action is taken. The agent never produces free-form
instructions that bypass validation.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class ApprovalMode(str, Enum):
    """Controls whether agent-generated plans require human approval."""

    MANUAL_APPROVAL = "manual_approval"   # Default: human must approve each action
    AUTO_APPROVE = "auto_approve"         # Agent plans auto-approved, but not auto-published
    AUTO_PUBLISH = "auto_publish"         # Full autonomy (requires explicit tenant opt-in)


class PlanStatus(str, Enum):
    """Lifecycle of a publishing plan."""

    DRAFT = "draft"             # Generated, awaiting review
    PENDING_APPROVAL = "pending_approval"  # Submitted for approval
    APPROVED = "approved"       # Approved, ready for execution
    REJECTED = "rejected"       # Rejected by human reviewer
    EXECUTING = "executing"     # Currently being converted to publishing jobs
    COMPLETED = "completed"     # All actions executed
    PARTIALLY_FAILED = "partially_failed"  # Some actions failed
    CANCELLED = "cancelled"     # Cancelled before execution


class ActionStatus(str, Enum):
    """Status of an individual action within a plan."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    QUEUED = "queued"       # Converted to a publishing job
    PUBLISHED = "published"
    FAILED = "failed"


@dataclass
class ContentVariant:
    """Platform-specific content adaptation generated by the AI agent."""

    platform: str
    content: str
    hashtags: list[str] = field(default_factory=list)
    tone: str = "professional"
    media_urls: list[str] = field(default_factory=list)
    caption_notes: str = ""  # Agent's reasoning for this variant

    @property
    def full_content(self) -> str:
        """Content with hashtags appended."""
        if not self.hashtags:
            return self.content
        tags = " ".join(f"#{tag}" for tag in self.hashtags)
        return f"{self.content}\n\n{tags}"


@dataclass
class ScheduledAction:
    """A single publishing action within a plan."""

    id: str
    platform: str
    account_id: str
    content_variant: ContentVariant
    scheduled_at: datetime
    status: ActionStatus = ActionStatus.PENDING
    rejection_reason: Optional[str] = None
    job_id: Optional[str] = None  # Linked publishing job after execution
    published_post_id: Optional[str] = None


@dataclass
class PublishingPlan:
    """A complete publishing plan generated by the AI agent.

    Contains one or more scheduled actions across platforms.
    Must be approved before execution (unless AUTO_PUBLISH mode).
    """

    id: str
    tenant_id: str
    title: str
    description: str
    actions: list[ScheduledAction] = field(default_factory=list)
    status: PlanStatus = PlanStatus.DRAFT
    approval_mode: ApprovalMode = ApprovalMode.MANUAL_APPROVAL
    source_content: str = ""    # Original user input
    campaign_days: int = 1      # Number of days in the campaign
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    approved_at: Optional[datetime] = None
    approved_by: Optional[str] = None
    rejection_reason: Optional[str] = None

    @property
    def action_count(self) -> int:
        return len(self.actions)

    @property
    def platform_summary(self) -> dict[str, int]:
        """Count of actions per platform."""
        counts: dict[str, int] = {}
        for action in self.actions:
            counts[action.platform] = counts.get(action.platform, 0) + 1
        return counts


@dataclass
class AgentDecision:
    """Metadata about an agent decision for audit/logging."""

    decision_type: str     # e.g., "content_generation", "schedule_recommendation"
    tenant_id: str
    input_summary: str     # What the user asked (truncated, no sensitive data)
    output_summary: str    # What the agent produced
    model_used: str = ""
    tokens_used: int = 0
    duration_ms: int = 0
    created_at: Optional[datetime] = None
